import { apiCatalog, recommendedStack } from "@/lib/api/contracts";
import { JOB_NAME_LIST } from "@/lib/job-names";
import { selectNextAssignment } from "@/lib/rotation-engine";
import type {
  ActivityRecord,
  ConversationRecord,
  DealershipSummary,
  EmployeeRecord,
  ParentAccountSummary,
  QueueItemRecord,
  ReportMetric,
  VehicleRecord,
} from "@/lib/types";

export const parentAccount: ParentAccountSummary = {
  id: "pa_pinnacle",
  name: "Pinnacle Auto Group",
  productName: "The Book",
  planName: "Pro",
  seatAllowance: 18,
  seatsUsed: 5,
  subscriptionStatus: "ACTIVE",
  dealershipCount: 1,
  inventorySourceLabel: "DealerSocket feed with webhook fallback",
  listingMode: "HUMAN_ASSISTED",
};

export const dealerships: DealershipSummary[] = [
  {
    id: "dlr_nashville",
    parentAccountId: "pa_pinnacle",
    name: "Pinnacle Nashville",
    city: "Nashville",
    state: "TN",
    timezone: "America/Chicago",
    inventorySourceStatus: "CONNECTED",
  },
];

export const employees: EmployeeRecord[] = [
  {
    id: "mem_marcus",
    dealershipId: "dlr_nashville",
    firstName: "Marcus",
    lastName: "Webb",
    displayName: "Marcus Webb",
    email: "marcus@pinnacleauto.com",
    role: "MANAGER",
    status: "ACTIVE",
    rotationPosition: 1,
    facebookStatus: "CONNECTED",
    liveListings: 12,
    openConversations: 3,
    assignmentsToday: 3,
    dailyListingLimit: 5,
    lastAssignedAt: "2026-03-24T13:15:00-05:00",
    notes: "Handles aged inventory well.",
  },
  {
    id: "mem_dana",
    dealershipId: "dlr_nashville",
    firstName: "Dana",
    lastName: "Torres",
    displayName: "Dana Torres",
    email: "dana@pinnacleauto.com",
    role: "EMPLOYEE",
    status: "ACTIVE",
    rotationPosition: 2,
    facebookStatus: "CONNECTED",
    liveListings: 8,
    openConversations: 7,
    assignmentsToday: 2,
    dailyListingLimit: 4,
    lastAssignedAt: "2026-03-24T14:20:00-05:00",
    notes: "Highest message response volume this week.",
  },
  {
    id: "mem_jamal",
    dealershipId: "dlr_nashville",
    firstName: "Jamal",
    lastName: "King",
    displayName: "Jamal King",
    email: "jamal@pinnacleauto.com",
    role: "EMPLOYEE",
    status: "ACTIVE",
    rotationPosition: 3,
    facebookStatus: "DISCONNECTED",
    liveListings: 5,
    openConversations: 1,
    assignmentsToday: 0,
    dailyListingLimit: 4,
    lastAssignedAt: "2026-03-23T16:30:00-05:00",
    notes: "Needs Facebook reconnection.",
  },
  {
    id: "mem_priya",
    dealershipId: "dlr_nashville",
    firstName: "Priya",
    lastName: "Nair",
    displayName: "Priya Nair",
    email: "priya@pinnacleauto.com",
    role: "EMPLOYEE",
    status: "INACTIVE",
    rotationPosition: 4,
    facebookStatus: "CONNECTED",
    liveListings: 0,
    openConversations: 0,
    assignmentsToday: 0,
    dailyListingLimit: 4,
    notes: "Out on leave.",
  },
  {
    id: "mem_seth",
    dealershipId: "dlr_nashville",
    firstName: "Seth",
    lastName: "Carlson",
    displayName: "Seth Carlson",
    email: "seth@pinnacleauto.com",
    role: "EMPLOYEE",
    status: "ACTIVE",
    rotationPosition: 5,
    facebookStatus: "CONNECTED",
    liveListings: 9,
    openConversations: 5,
    assignmentsToday: 1,
    dailyListingLimit: 4,
    lastAssignedAt: "2026-03-24T09:45:00-05:00",
    notes: "Best conversion rate on trucks.",
  },
];

export const vehicles: VehicleRecord[] = [
  {
    id: "veh_f150",
    dealershipId: "dlr_nashville",
    sourceId: "src_dealersocket",
    stockNumber: "A1234",
    vin: "1FTFW1E50MFA12345",
    year: 2021,
    make: "Ford",
    model: "F-150",
    trim: "XLT 4WD",
    priceCents: 3490000,
    mileage: 28450,
    daysOnLot: 12,
    lifecycleStatus: "IN_STOCK",
    listingStatus: "POSTED",
    listedByMembershipId: "mem_marcus",
    imageCount: 18,
    exteriorColor: "Oxford White",
    updatedAt: "2026-03-24T15:02:00-05:00",
  },
  {
    id: "veh_silverado",
    dealershipId: "dlr_nashville",
    sourceId: "src_dealersocket",
    stockNumber: "A1235",
    vin: "1GCUYEED9NZ543210",
    year: 2022,
    make: "Chevrolet",
    model: "Silverado 1500",
    trim: "LT Trail Boss",
    priceCents: 4250000,
    mileage: 14200,
    daysOnLot: 5,
    lifecycleStatus: "IN_STOCK",
    listingStatus: "POSTED",
    listedByMembershipId: "mem_dana",
    imageCount: 22,
    exteriorColor: "Black",
    updatedAt: "2026-03-24T14:50:00-05:00",
  },
  {
    id: "veh_camry",
    dealershipId: "dlr_nashville",
    sourceId: "src_dealersocket",
    stockNumber: "A1236",
    vin: "4T1G11AK2LU998877",
    year: 2020,
    make: "Toyota",
    model: "Camry",
    trim: "SE",
    priceCents: 2240000,
    mileage: 41300,
    daysOnLot: 31,
    lifecycleStatus: "IN_STOCK",
    listingStatus: "DRAFT_READY",
    listedByMembershipId: "mem_seth",
    imageCount: 15,
    exteriorColor: "Celestial Silver",
    updatedAt: "2026-03-24T15:07:00-05:00",
  },
  {
    id: "veh_crv",
    dealershipId: "dlr_nashville",
    sourceId: "src_dealersocket",
    stockNumber: "A1237",
    vin: "2HKRW2H89PH765432",
    year: 2023,
    make: "Honda",
    model: "CR-V",
    trim: "EX-L AWD",
    priceCents: 3180000,
    mileage: 6200,
    daysOnLot: 3,
    lifecycleStatus: "IN_STOCK",
    listingStatus: "POSTED",
    listedByMembershipId: "mem_seth",
    imageCount: 19,
    exteriorColor: "Still Night Pearl",
    updatedAt: "2026-03-24T12:55:00-05:00",
  },
  {
    id: "veh_ram",
    dealershipId: "dlr_nashville",
    sourceId: "src_dealersocket",
    stockNumber: "A1238",
    vin: "1C6SRFFT1KN123321",
    year: 2019,
    make: "RAM",
    model: "1500",
    trim: "Big Horn 4x4",
    priceCents: 2960000,
    mileage: 58700,
    daysOnLot: 47,
    lifecycleStatus: "IN_STOCK",
    listingStatus: "QUEUED",
    imageCount: 16,
    exteriorColor: "Patriot Blue",
    updatedAt: "2026-03-24T14:12:00-05:00",
  },
  {
    id: "veh_jeep",
    dealershipId: "dlr_nashville",
    sourceId: "src_dealersocket",
    stockNumber: "A1239",
    vin: "1C4RJFAG6NC112233",
    year: 2022,
    make: "Jeep",
    model: "Grand Cherokee",
    trim: "Laredo 4x4",
    priceCents: 3620000,
    mileage: 19800,
    daysOnLot: 18,
    lifecycleStatus: "IN_STOCK",
    listingStatus: "POSTED",
    listedByMembershipId: "mem_seth",
    imageCount: 21,
    exteriorColor: "Bright White",
    updatedAt: "2026-03-24T15:10:00-05:00",
  },
  {
    id: "veh_sierra",
    dealershipId: "dlr_nashville",
    sourceId: "src_dealersocket",
    stockNumber: "A1240",
    vin: "3GTUUBED4MG556677",
    year: 2021,
    make: "GMC",
    model: "Sierra 1500",
    trim: "SLE 4WD",
    priceCents: 3810000,
    mileage: 23100,
    daysOnLot: 22,
    lifecycleStatus: "IN_STOCK",
    listingStatus: "ELIGIBLE",
    imageCount: 20,
    exteriorColor: "Summit White",
    updatedAt: "2026-03-24T14:41:00-05:00",
  },
  {
    id: "veh_outback",
    dealershipId: "dlr_nashville",
    sourceId: "src_dealersocket",
    stockNumber: "A1241",
    vin: "4S4BTACC5L3111222",
    year: 2020,
    make: "Subaru",
    model: "Outback",
    trim: "Premium AWD",
    priceCents: 2490000,
    mileage: 35600,
    daysOnLot: 8,
    lifecycleStatus: "IN_STOCK",
    listingStatus: "POSTED",
    listedByMembershipId: "mem_marcus",
    imageCount: 17,
    exteriorColor: "Autumn Green",
    updatedAt: "2026-03-24T11:16:00-05:00",
  },
  {
    id: "veh_tacoma",
    dealershipId: "dlr_nashville",
    sourceId: "src_dealersocket",
    stockNumber: "A1242",
    vin: "3TMCZ5AN7PM221144",
    year: 2023,
    make: "Toyota",
    model: "Tacoma",
    trim: "TRD Off-Road 4x4",
    priceCents: 4410000,
    mileage: 4800,
    daysOnLot: 2,
    lifecycleStatus: "IN_STOCK",
    listingStatus: "POSTED",
    listedByMembershipId: "mem_dana",
    imageCount: 23,
    exteriorColor: "Ice Cap",
    updatedAt: "2026-03-24T15:09:00-05:00",
  },
  {
    id: "veh_frontier",
    dealershipId: "dlr_nashville",
    sourceId: "src_dealersocket",
    stockNumber: "A1243",
    vin: "1N6ED1EK2MN778899",
    year: 2021,
    make: "Nissan",
    model: "Frontier",
    trim: "Pro-4X 4WD",
    priceCents: 3150000,
    mileage: 19200,
    daysOnLot: 14,
    lifecycleStatus: "IN_STOCK",
    listingStatus: "NEEDS_REVIEW",
    listedByMembershipId: "mem_marcus",
    imageCount: 18,
    exteriorColor: "Gun Metallic",
    updatedAt: "2026-03-24T13:03:00-05:00",
  },
];

export const queueItems: QueueItemRecord[] = [
  {
    id: "job_1",
    vehicleId: "veh_sierra",
    vehicleLabel: "2021 GMC Sierra 1500 SLE 4WD",
    assignedMembershipId: "mem_dana",
    scheduledFor: "2026-03-24T15:00:00-05:00",
    status: "READY",
    jobType: "LISTING_ASSIGNMENT",
    mode: "HUMAN_ASSISTED",
    reason: "Eligible inventory hit age threshold without active listing.",
    retryCount: 0,
  },
  {
    id: "job_2",
    vehicleId: "veh_camry",
    vehicleLabel: "2020 Toyota Camry SE",
    assignedMembershipId: "mem_seth",
    scheduledFor: "2026-03-24T16:30:00-05:00",
    status: "PENDING",
    jobType: "DRAFT_GENERATION",
    mode: "HUMAN_ASSISTED",
    reason: "Draft regenerated after price update from DMS.",
    retryCount: 1,
  },
  {
    id: "job_3",
    vehicleId: "veh_ram",
    vehicleLabel: "2019 RAM 1500 Big Horn 4x4",
    assignedMembershipId: "mem_seth",
    scheduledFor: "2026-03-25T09:00:00-05:00",
    status: "PENDING",
    jobType: "PUBLISH_ATTEMPT",
    mode: "HUMAN_ASSISTED",
    reason: "Human follow-up reminder to publish from approved draft.",
    retryCount: 0,
  },
  {
    id: "job_4",
    vehicleId: "veh_frontier",
    vehicleLabel: "2021 Nissan Frontier Pro-4X",
    assignedMembershipId: "mem_marcus",
    scheduledFor: "2026-03-25T11:00:00-05:00",
    status: "RETRY_SCHEDULED",
    jobType: "PUBLISH_ATTEMPT",
    mode: "HUMAN_ASSISTED",
    reason: "Image quality warning requires a human review before republish.",
    retryCount: 2,
  },
];

export const conversations: ConversationRecord[] = [
  {
    id: "convo_1",
    tenantId: "dlr_nashville",
    vehicleId: "veh_f150",
    customerName: "Ryan Mitchell",
    vehicleLabel: "2021 Ford F-150 XLT 4WD",
    assignedMembershipId: "mem_marcus",
    channel: "FACEBOOK_MARKETPLACE",
    status: "OPEN",
    unreadCount: 1,
    escalated: false,
    lastMessageAt: "2026-03-24T15:28:00-05:00",
    lastPreview: "Is this truck still available tomorrow morning?",
    notesCount: 1,
    messages: [
      {
        id: "msg_1",
        direction: "INBOUND",
        body: "Is this truck still available tomorrow morning?",
        sentAt: "2026-03-24T15:28:00-05:00",
        authorName: "Ryan Mitchell",
      },
      {
        id: "msg_2",
        direction: "OUTBOUND",
        body: "Yes, it is. I can hold a 10 AM appointment if you want it.",
        sentAt: "2026-03-24T15:31:00-05:00",
        authorName: "Marcus Webb",
      },
      {
        id: "msg_3",
        direction: "INTERNAL_NOTE",
        body: "Customer asked about tow package. Confirm before arrival.",
        sentAt: "2026-03-24T15:34:00-05:00",
        authorName: "Marcus Webb",
      },
    ],
  },
  {
    id: "convo_2",
    tenantId: "dlr_nashville",
    vehicleId: "veh_silverado",
    customerName: "Cassandra Lee",
    vehicleLabel: "2022 Chevrolet Silverado 1500 LT Trail Boss",
    assignedMembershipId: "mem_dana",
    channel: "FACEBOOK_MARKETPLACE",
    status: "PENDING_EMPLOYEE",
    unreadCount: 2,
    escalated: true,
    lastMessageAt: "2026-03-24T14:52:00-05:00",
    lastPreview: "What is the best price if I finance today?",
    notesCount: 2,
    messages: [
      {
        id: "msg_4",
        direction: "INBOUND",
        body: "What is the best price if I finance today?",
        sentAt: "2026-03-24T14:52:00-05:00",
        authorName: "Cassandra Lee",
      },
      {
        id: "msg_5",
        direction: "INTERNAL_NOTE",
        body: "Escalated to manager for pricing approval.",
        sentAt: "2026-03-24T14:57:00-05:00",
        authorName: "Dana Torres",
      },
    ],
  },
  {
    id: "convo_3",
    tenantId: "dlr_nashville",
    vehicleId: "veh_jeep",
    customerName: "Tom Brewer",
    vehicleLabel: "2022 Jeep Grand Cherokee Laredo 4x4",
    assignedMembershipId: "mem_seth",
    channel: "FACEBOOK_MARKETPLACE",
    status: "OPEN",
    unreadCount: 1,
    escalated: false,
    lastMessageAt: "2026-03-24T13:14:00-05:00",
    lastPreview: "If the payment is around $550, I can come by tonight.",
    notesCount: 0,
    messages: [
      {
        id: "msg_6",
        direction: "INBOUND",
        body: "Does it have a sunroof?",
        sentAt: "2026-03-24T13:05:00-05:00",
        authorName: "Tom Brewer",
      },
      {
        id: "msg_7",
        direction: "OUTBOUND",
        body: "Yes, it has the panoramic roof. Want a walkaround video?",
        sentAt: "2026-03-24T13:09:00-05:00",
        authorName: "Seth Carlson",
      },
      {
        id: "msg_10",
        direction: "INBOUND",
        body: "If the payment is around $550, I can come by tonight.",
        sentAt: "2026-03-24T13:14:00-05:00",
        authorName: "Tom Brewer",
      },
    ],
  },
  {
    id: "convo_4",
    tenantId: "dlr_nashville",
    vehicleId: "veh_crv",
    customerName: "Maria Santos",
    vehicleLabel: "2023 Honda CR-V EX-L AWD",
    assignedMembershipId: "mem_seth",
    channel: "FACEBOOK_MARKETPLACE",
    status: "OPEN",
    unreadCount: 1,
    escalated: false,
    lastMessageAt: "2026-03-24T11:26:00-05:00",
    lastPreview: "10 AM works for me. Please lock it in.",
    notesCount: 1,
    messages: [
      {
        id: "msg_8",
        direction: "INBOUND",
        body: "Can I schedule a test drive for Saturday?",
        sentAt: "2026-03-24T11:14:00-05:00",
        authorName: "Maria Santos",
      },
      {
        id: "msg_9",
        direction: "OUTBOUND",
        body: "Saturday at 10 AM is open. I can reserve it for you now.",
        sentAt: "2026-03-24T11:21:00-05:00",
        authorName: "Seth Carlson",
      },
      {
        id: "msg_11",
        direction: "INBOUND",
        body: "10 AM works for me. Please lock it in.",
        sentAt: "2026-03-24T11:26:00-05:00",
        authorName: "Maria Santos",
      },
    ],
  },
];

export const activityFeed: ActivityRecord[] = [
  {
    id: "activity_1",
    kind: "inventory_sync",
    tone: "navy",
    message: "Inventory sync completed. 10 vehicles normalized from DealerSocket.",
    createdAt: "2026-03-24T15:12:00-05:00",
  },
  {
    id: "activity_2",
    kind: "listing_assigned",
    tone: "forest",
    message: "The Book assigned 2021 GMC Sierra 1500 to Dana Torres.",
    createdAt: "2026-03-24T15:02:00-05:00",
  },
  {
    id: "activity_3",
    kind: "social_warning",
    tone: "tan",
    message: "Jamal King was skipped because Facebook is disconnected.",
    createdAt: "2026-03-24T14:58:00-05:00",
  },
  {
    id: "activity_4",
    kind: "conversation_escalated",
    tone: "danger",
    message: "Dana escalated Silverado pricing approval to a manager.",
    createdAt: "2026-03-24T14:57:00-05:00",
  },
];

export const reportMetrics: ReportMetric[] = [
  {
    id: "metric_1",
    label: "Live listings",
    value: "6",
    change: "+2 this week",
    tone: "forest",
  },
  {
    id: "metric_2",
    label: "Inventory coverage",
    value: "60%",
    change: "4 vehicles still unlisted",
    tone: "navy",
  },
  {
    id: "metric_3",
    label: "Median time to listing",
    value: "3.7h",
    change: "-1.2h from last week",
    tone: "forest",
  },
  {
    id: "metric_4",
    label: "Unread inbox load",
    value: "4",
    change: "1 conversation escalated",
    tone: "tan",
  },
];

export const dailyListingSeries = [
  { label: "Mon", value: 4 },
  { label: "Tue", value: 5 },
  { label: "Wed", value: 3 },
  { label: "Thu", value: 6 },
  { label: "Fri", value: 4 },
  { label: "Sat", value: 2 },
  { label: "Sun", value: 1 },
];

export const responseVolumeByEmployee = [
  { label: "Marcus", value: 12 },
  { label: "Dana", value: 18 },
  { label: "Jamal", value: 3 },
  { label: "Priya", value: 0 },
  { label: "Seth", value: 14 },
];

export const nextRotationDecision = selectNextAssignment({
  employees,
  vehicle: vehicles.find((vehicle) => vehicle.id === "veh_sierra")!,
  queueItems,
  activeVehicleListingIds: vehicles
    .filter((vehicle) => vehicle.listingStatus === "POSTED")
    .map((vehicle) => vehicle.id),
  cursorMembershipId: "mem_marcus",
  cooldownMinutes: 60,
  maxPendingAssignmentsPerEmployee: 3,
  now: "2026-03-24T15:00:00-05:00",
});

export const coverageCount = vehicles.filter(
  (vehicle) => vehicle.listingStatus === "POSTED",
).length;
export const eligibleCount = vehicles.filter(
  (vehicle) => vehicle.listingStatus === "ELIGIBLE",
).length;
export const staleInventoryCount = vehicles.filter(
  (vehicle) => vehicle.daysOnLot >= 30,
).length;
export const unreadConversationCount = conversations.reduce(
  (total, conversation) => total + conversation.unreadCount,
  0,
);

export const stackChoices = recommendedStack;
export const endpointCatalog = apiCatalog;
export const queueJobNames = JOB_NAME_LIST;
